<script type="text/javascript">
    google_ad_client = "ca-pub-7125508701171835";
    google_ad_slot = "1763269130";
    google_ad_width = 336;
    google_ad_height = 280;
</script>
<!-- cep101 -->
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- cep блок ссылок -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7125508701171835"
     data-ad-slot="2558264013"
     data-ad-format="link"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>