

<!-- реклама ситиадс, по которой была за€вка 800р -->
<div class="leftrubrika">
<table width="100%" border="0" cellspacing="0" cellpadding="5">
<tr><td colspan="2" style="background-color: #069; padding-left: 10px;"><font color="#FFFFFF"><strong>–еклама</strong></font></td></tr>
<tr><td><script language="JavaScript" type="text/javascript">
(function() {var d=document; var s=d.createElement('script'); var id = Math.floor(Math.random()*999);d.write('<div id="x'+id+'"></div>');s.type = 'text/javascript';s.async = true;s.src = 'http://gameleads.ru/counter.php?ban_id=23298&size=200x200&cid=d7a268ae0b4c8972242c7dd9d15af1b5&sa=&dv='+id; var x=d.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); })();
</script></td></tr>

</table>
</div>


<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td width="50%"><table border="0" cellspacing="0" cellpadding="0"><tr><td><h4><a href="#">–усский стандарт</a></h4></td> <td><img src="images/visa.png" alt="" width="69" height="22" hspace="10" border="0" align="middle"></td></tr></table></td><td width="50%"><table border="0" cellspacing="0" cellpadding="0"><tr><td><h4><a href="#">Ѕанк “раст</a></h4></td><td><img src="images/visa2.png" alt="" width="38" height="21" hspace="10" border="0" align="middle"></td></tr></table></td></tr>
<tr><td width="50%"><img src="images/rsb.png" alt="" width="236" height="149" vspace="10" border="0"></td><td width="50%"><img src="images/trust.png" alt="" width="236" height="150" vspace="10" border="0"></td></tr>
<tr><td valign="top">
<div class="index-cards">
<p><ul>
<li> редитна€ карта дл€ повседневной жизни.</li>
<li> редитный лимит Ч до 450 000 рублей.</li>
<li>ѕроцентна€ ставка на операции Ч 36% годовых.</li>
<li>Ћьготный период кредитовани€ Ч до 55 дней.</li>
</ul></p>
</div>
<a href="#"><img src="images/oform.png" alt="" width="169" height="47" border="0"></a>
</td>
<td valign="top">
<div class="index-cards">
<p><ul>
<li>¬ыгодно от 12,9% годовых за кредит. </li>
<li>Ѕыстро оформление за 15 минут.</li>
<li>Ћьготный период с 0% ставкой до 55 дней.</li>
<li>ќбслуживание карты бесплатно.</li>
</ul></p>
</div>
<a href="#"><img src="images/oform.png" alt="" width="169" height="47" border="0"></a>
</td>
</tr>
</table>