<br>




<script type="text/javascript"><!--
google_ad_client = "ca-pub-7125508701171835";
/* cep down 580x400 */
google_ad_slot = "5500906736";
google_ad_width = 580;
google_ad_height = 400;
//-->
</script>
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>



<br>

<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj"></div> 




		<!-- БЛОК ССЫЛОК СНИЗУ -->
		<div class="comments_divs">
				<!-- комментарии -->
				<?require_once ($_SERVER['DOCUMENT_ROOT'].'/commentit/comment.php');?>
				<!-- КОНЕЦ комментарии -->
		</div>

</div>
		</div>
		
		<footer class="footer clear">
			<div class="footer_left">
			<p>&copy; 2011—<?php echo date('Y'); ?> <a href="/">Проект «Доступно о финансах»</a> <br>



	<a href="mailto:admin@landshaftagreg.ru">Обратная связь</a> | <a href="/sitemap.html">Карта сайта</a> | <a href="/ad/">Реклама на сайте</a><br>
	При использовании материалов данного сайта гиперссылка на сайт обязательна</p></div>
			<div class="footer_right">

		<?
		if ($metka == "mycounter")
		{
		include ('mycounter.inc');
		}
		else
		{
		echo "&nbsp;";
		}
		?>

	
			</div>
		</footer>
		
	</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5998499-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	<script type="text/javascript" src="/js/adaptive.js"></script>
</body>
</html>
  
  
  