
<br>


  



		<?
		if ($stranica == "index")
		{
		echo "&nbsp;";
		}
		else
		{
		include ('down-rubriki.inc');
		}
		?>




</td></tr></table>
<!-- конец таблица внутри главного окна -->


</td></tr>
<tr><td bgcolor="#666666" background="/images/bgmenudown.jpg" style="padding: 10px">

	
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr><td width="100%">
	<div class="footer"><p>&copy; 2011—<?php echo date('Y'); ?> <a href="/">Проект «Доступно о финансах»</a> <br>



	<a href="mailto:admin@landshaftagreg.ru">Обратная связь</a> | <a href="/sitemap.html">Карта сайта</a> | <a href="/ad/">Реклама на сайте</a><br>
	При использовании материалов данного сайта гиперссылка на сайт обязательна</p></div>
	</td>
	<td align="right">
<table><tr><td>

		<?
		if ($metka == "mycounter")
		{
		include ('mycounter.inc');
		}
		else
		{
		echo "&nbsp;";
		}
		?>

	</td>
<td>	

<!-- LI -->



</td></tr></table>

	</td>
	</tr></table>

</td></tr></table>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5998499-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>
  
  
  