

<!-- шапка -->
<table width="100%" border="0" cellspacing="0" cellpadding="0"><tr><td><a href="/"><img src="/images/core/logo260.jpg" alt="На главную" width="260" height="100" border="0"></a></td><td width="100%" align="center" valign="middle" bgcolor="#FFFFFF" style="padding:5px"><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="600" height="82" id="jook-invest" align="middle">
	<param name="allowScriptAccess" value="sameDomain" />
	<param name="allowFullScreen" value="false" />
	<param name="movie" value="/banner.swf" /><param name="quality" value="high" /><param name="bgcolor" value="#336699" />	<embed src="/banner.swf" quality="high" bgcolor="#336699" width="600" height="82" name="jook-invest" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" />
	</object></td></tr></table>
<!-- ///шапка -->