




<noindex>
<div class="table12">
<table border="0" cellspacing="0" cellpadding="0" class="credit_liner"><caption>ТОП-7 самых популярных предложения за последние 3 месяца:</caption>
<tr>
	<th colspan="2">Банк</th>
	<th>Максимальная сумма кредита</th>
	<th>Заявка онлайн</th>
</tr>

<tr>
	<td><a href="/inc/cpa/credit/tinkoff.php" target="_blank"><img src="../../images/bank/tinkoff.png" width="143" height="43" border="0" class="pad"></a></td>
	<td>Тинькофф Platinum — кредитная карта, <strong>0%</strong> годовых на все покупки по карте <strong>до 55 дней</strong><br> Рейтинг: <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"></td>
	<td>До 300 000 рублей</td>
	<td><a href="/inc/cpa/credit/tinkoff.php" target="_blank"><img src="/images/core/zayavka.png"  width="129" height="35" border="0"></a></td>
</tr>
<tr>
	<td><a href="/inc/cpa/credit/ren.php" target="_blank"><img src="../../images/ren.jpg" alt="" width="143" height="59" border="0" class="pad"></a></td>
	<td>Ренессанс Кредит — ставка <strong>от 11,3%</strong> годовых! До 5 лет!<br> Рейтинг: <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"></td>
	<td>До 700 000 рублей</td>
	<td><a href="/inc/cpa/credit/ren.php" target="_blank"><img src="/images/core/zayavka.png"  width="129" height="35" border="0"></a></td>
</tr>
<tr>
	<td><a href="/inc/cpa/credit/vost.php" target="_blank"><img src="/images/bank/vost.png" alt="" width="143" height="50" border="0" class="pad"></a></td>
	<td>Восточный банк — Кредит на любые цели. Срок до 3х лет, <strong>без справок и поручителей</strong><br> Рейтинг: <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"></td>
	<td>До 200 000 рублей</td>
	<td><a href="/inc/cpa/credit/vost.php" target="_blank"><img src="/images/core/zayavka.png"  width="129" height="35" border="0"></a></td>
</tr>
<tr>
	<td><a href="/inc/cpa/credit/sov.php" target="_blank"><img src="../../images/bank/sovkom.png" alt="" width="143" height="50" border="0" class="pad"></a></td>
	<td>Совкомбанк Денежный кредит <strong>под 12%</strong>, на 12 месяцев
	<br> Рейтинг: <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <font size="+1" color="#FF0000">ХИТ!</font>
	</td>
	<td>100 тысяч рублей</td>
	<td><a href="/inc/cpa/credit/sov.php" target="_blank"><img src="/images/core/zayavka.png"  width="129" height="35" border="0"></a></td>
</tr>


<tr>
	<td><a href="/inc/cpa/credit/skb.php" target="_blank"><img src="/images/bank/skb.png" alt="" width="143" height="50" border="0" class="pad"></a></td>
	<td>СКБ банк <strong>от 11,9%</strong> годовых! Без комиссий!<br> Рейтинг: <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-on.png" width="16" height="16" border="0"> <img src="/images/bank/star-off.png" width="16" height="16" border="0"></td>
	<td>До 1 300 000 рублей</td>
	<td><a href="/inc/cpa/credit/skb.php" target="_blank"><img src="/images/core/zayavka.png"  width="129" height="35" border="0"></a></td>
</tr>











</table>
</div>
</noindex>
<br><br>